package com.cxtx.user_manage.web.rest;


import com.cxtx.common.unit.ResponseUtil;
import com.github.pagehelper.PageInfo;

import com.cxtx.user_manage.domain.OaFlowForm;
import com.cxtx.user_manage.service.OaFlowFormService;
import io.swagger.annotations.*;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.HttpStatus;
import org.springframework.http.ResponseEntity;
import org.springframework.web.bind.annotation.*;
import springfox.documentation.annotations.ApiIgnore;

import javax.validation.Valid;
import java.net.URISyntaxException;
import java.util.Map;

/**
 * REST controller for managing oaFlowForms.
 * <p>
 * generated by Handsmap New Technology R&D Center  on 2021-7-16 9:39:26
 * create by sliu
 */
@Api(tags = "OaFlowForm")
@RestController
@RequestMapping("/api")
public class OaFlowFormResource {

    private final Logger log = LoggerFactory.getLogger(OaFlowFormResource.class);

    private static final String ENTITY_NAME = "oaFlowForm";

    @Autowired
    private OaFlowFormService oaFlowFormService;

    /**
     * POST  /oaFlowForms  : Creates a new oaFlowForm.
     *
     * @param oaFlowForm the oaFlowForm to create
     * @return the ResponseEntity with status 200
     * @throws URISyntaxException if the Location URI syntax is incorrect
     */
    @ApiOperation(value = "新增__OaFlowForm__", notes = "新增一个__OaFlowForm__", response = ResponseUtil.Response.class)
    @ApiImplicitParam(name = "oaFlowForm", value = "__OaFlowForm__", required = true, paramType = "body", dataType = "OaFlowForm")
    @PostMapping("/oaFlowForms")
    public ResponseEntity<Map> createOaFlowForm(@Valid @RequestBody OaFlowForm oaFlowForm) throws URISyntaxException {
        log.debug("REST request to save OaFlowForm : {}", oaFlowForm);
        try {
            int result = oaFlowFormService.insertSelective(oaFlowForm);
            if (result == 1) {
                return ResponseUtil.success("");
            } else {
                return ResponseUtil.error("新增失败！");
            }
        }catch (Exception e){
        return ResponseUtil.error(e.getMessage());
        }
    }

    /**
     * PUT  /oaFlowForms : Updates an existing OaFlowForm.
     *
     * @param oaFlowForm the oaFlowForm to update
     * @return the ResponseEntity with status 200 (OK) and with body the updated oaFlowForm,
     * or with status 500 (Internal Server Error) if the oaFlowForm couldn't be updated
     */
    @ApiOperation(value = "更新__OaFlowForm__", notes = "根据指定wid 更新一个__OaFlowForm__", response = ResponseUtil.Response.class)
    @ApiImplicitParam(name = "oaFlowForm", value = "__OaFlowForm__", required = true, paramType = "body", dataType = "OaFlowForm")
    @PutMapping("/oaFlowForms")
    public ResponseEntity<Map> updateOaFlowForm(@Valid @RequestBody OaFlowForm oaFlowForm) {
        log.debug("REST request to update OaFlowForm : {}", oaFlowForm);
        try {
            int result = oaFlowFormService.updateByPrimaryKeySelective(oaFlowForm);
            if (result == 1) {
                return ResponseUtil.success("");
            } else {
                return ResponseUtil.error("更新失败");
            }
        }catch (Exception e){
            return ResponseUtil.error(e.getMessage());
        }
    }

    /**
     * GET  /oaFlowForms : get all oaFlowForms.
     *
     * @return the ResponseEntity with status 200 (OK) and with body all oaFlowForms
     */
    @GetMapping("/oaFlowForms")
    @ApiOperation(value = "分页获取__OaFlowForm__", notes = "分页获取__OaFlowForm__列表", response = ResponseUtil.Response.class)
    @ApiImplicitParams(
            value = {
                    @ApiImplicitParam(name = "pageNum", value = "分页参数：第几页", required = true, paramType = "query", dataType = "int"),
                    @ApiImplicitParam(name = "pageSize", value = "分页参数：每页数量", required = true, paramType = "query", dataType = "int")
            }
    )
    public ResponseEntity<Map> queryByPageOaFlowForms(@ApiIgnore @RequestParam Map params) {
        try {
            PageInfo<OaFlowForm> result = oaFlowFormService.queryByPage(params);
            if (result != null) {
                return ResponseUtil.success(result);
            } else {
                return ResponseUtil.error("有错误");
            }
        }catch (Exception e){
            return ResponseUtil.error(e.getMessage());
        }
    }


    /**
     * GET  /oaFlowForms/id : get  oaFlowForm by id.
     *
     * @return the ResponseEntity with status 200 (OK) and with body all oaFlowForms
     */
    @ApiOperation(value = "获取__OaFlowForm__", notes = "根据wid 获取一个__OaFlowForm__", response = ResponseUtil.Response.class)
    @ApiImplicitParam(name = "id", value = "id", required = true, paramType = "path")
    @GetMapping("/oaFlowForms/{id}")
    public ResponseEntity<Map> getOaFlowForm(@PathVariable Long id) {
        OaFlowForm result = oaFlowFormService.selectByPrimaryKey(id);
        if (result != null) {
            return ResponseUtil.success(result);
        } else {
            return ResponseUtil.error("获取失败！");
        }
    }

    /**
     * DELETE /oaFlowForms/:login : delete the "login" OaFlowForm.
     *
     * @param id the login of the oaFlowForm to delete
     * @return the ResponseEntity with status 200 (OK)
     */
    @ApiOperation(value = "删除__OaFlowForm__", notes = "根据wid 删除一个__OaFlowForm__", response = ResponseUtil.Response.class)
    @ApiImplicitParam(name = "id", value = "id", required = true, paramType = "path")
    @DeleteMapping("/oaFlowForms/{id}")
    public ResponseEntity<Map> deleteOaFlowForm(@PathVariable Long id) {
        log.debug("REST request to delete OaFlowForm: {}", id);
        int result = oaFlowFormService.deleteByPrimaryKey(id);
        if(result == 1){
            return ResponseUtil.success("删除成功！");
        }else{
            return ResponseUtil.error("删除失败！");
        }
    }

}
