server:
  port: 7001
  servlet:
    context-path: /authservice
spring:
  profiles:
    active: test


mybatis:
  mapper-locations: classpath*:config/mybatis/mappers/mysql/**/*.xml
  config-location: classpath:config/mybatis/config/mysql/mybatis-config.xml


