package com.cxtx.user_manage.service;

import com.github.pagehelper.PageInfo;
import com.cxtx.user_manage.domain.OaProcess;
import java.util.List;
import java.util.Map;

/**
 * OaProcess业务接口
 * <p>
 * generated by Handsmap New Technology R&D Center  on 2021-7-16 10:46:04
 * create by sliu
 */

public interface OaProcessService{

    int deleteByPrimaryKey(Long id);

    int insertSelective(OaProcess record);

    OaProcess selectByPrimaryKey(Long id);

    int updateByPrimaryKeySelective(OaProcess record);

    PageInfo<OaProcess> queryByPage(Map params);

    List<OaProcess> selectAll(Map params);
}