server:
  port: 7004
  servlet:
    context-path: /usermanage

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.117.128.180:3306/user_manage?serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: usermanage
    password: 12345678

logging:
  level:
    com:
      cxtx:
        user_manage:
          web:
            client:
              thirdparty:
                AMapClient: DEBUG

upload-path: C:/root/cxtx/image

