server:
  port: 7004
  servlet:
    context-path: /usermanage

spring:
  profiles:
    active: test


knife4j:
  enable: true
  setting:
    enableDocumentManage: true

mybatis:
  mapper-locations: classpath*:config/mybatis/mappers/mysql/**/*.xml
  config-location: classpath:config/mybatis/config/mysql/mybatis-frame.xml

logging:
  level:
    com:
      cxtx:
        user_manage:
          web:
            client:
              thirdparty:
                AMapClient: DEBUG


