server:
  port: 7004
  servlet:
    context-path: /usermanage

spring:
  application:
    name: user-manage

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://47.117.128.180:3306/user_manage?serverTimezone=Asia/Shanghai&useSSL=false&autoReconnect=true&allowMultiQueries=true&useUnicode=true&characterEncoding=utf8
    username: usermanage
    password: 12345678

  cloud:
    nacos:
      discovery:
        server-addr: 47.117.128.180:8848


mybatis:
  mapper-locations: classpath*:config/mybatis/mappers/mysql/**/*.xml
  config-location: classpath:config/mybatis/config/mysql/mybatis-frame.xml


logging:
  level:
    com:
      cxtx:
        user_manage:
          web:
            client:
              thirdparty:
                AMapClient: DEBUG

upload-path: C:/root/cxtx/image