server:
  port: 7002
  servlet:
    context-path: /scemanage
spring:
  profiles:
    active: test

mybatis:
  mapper-locations: classpath*:config/mybatis/mappers/mysql/**/*.xml
  config-location: classpath:config/mybatis/config/mysql/mybatis-config.xml






