
spring:
  profiles: test
  redis:
    host: 121.40.97.206
    port: 6379
    password: caojian




logging:
  config: classpath:logback-spring.xml
  file:
    #spring boot admin 要读取的日志文件位置
    name: /opt/test/logs/cxtx-gateway.log
    path: /opt/test/logs


